# This is the numpy focused portion of things

In [71]:
import numpy as np


In [3]:
np.__version__

'1.9.2'

In [24]:
w = np.array([[1,2,3,4],[5,6,7,8]])

In [25]:
print w

[[1 2 3 4]
 [5 6 7 8]]


In [27]:
np.reshape(w, (4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
w.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
a = np.zeros((10,2))

In [31]:
b = np.zeros([10,2])

In [39]:
c.shape = (20)

In [40]:
c

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [45]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [54]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
b = np.arange(12).reshape(3,4)

In [59]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
b.ravel()

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [66]:
np.ravel(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
b.ravel(order = "F")

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [68]:
np.ravel(b,order = "F")

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

# This is the Pandas Portion of things

In [72]:
import pandas as pd

In [87]:
dates = pd.date_range("20161031","20161225",freq = "D")

In [88]:
dates

DatetimeIndex(['2016-10-31', '2016-11-01', '2016-11-02', '2016-11-03',
               '2016-11-04', '2016-11-05', '2016-11-06', '2016-11-07',
               '2016-11-08', '2016-11-09', '2016-11-10', '2016-11-11',
               '2016-11-12', '2016-11-13', '2016-11-14', '2016-11-15',
               '2016-11-16', '2016-11-17', '2016-11-18', '2016-11-19',
               '2016-11-20', '2016-11-21', '2016-11-22', '2016-11-23',
               '2016-11-24', '2016-11-25', '2016-11-26', '2016-11-27',
               '2016-11-28', '2016-11-29', '2016-11-30', '2016-12-01',
               '2016-12-02', '2016-12-03', '2016-12-04', '2016-12-05',
               '2016-12-06', '2016-12-07', '2016-12-08', '2016-12-09',
               '2016-12-10', '2016-12-11', '2016-12-12', '2016-12-13',
               '2016-12-14', '2016-12-15', '2016-12-16', '2016-12-17',
               '2016-12-18', '2016-12-19', '2016-12-20', '2016-12-21',
               '2016-12-22', '2016-12-23', '2016-12-24', '2016-12-25'],
     

In [75]:
type(dates)

pandas.tseries.index.DatetimeIndex

In [76]:
for x in dates:
    print x

2016-01-01 00:00:00
2016-01-02 00:00:00
2016-01-03 00:00:00
2016-01-04 00:00:00
2016-01-05 00:00:00
2016-01-06 00:00:00
2016-01-07 00:00:00
2016-01-08 00:00:00
2016-01-09 00:00:00
2016-01-10 00:00:00
2016-01-11 00:00:00
2016-01-12 00:00:00
2016-01-13 00:00:00
2016-01-14 00:00:00


In [96]:
dates = pd.date_range("20160101",periods = 12, freq = "M")
print dates

DatetimeIndex(['2016-01-31', '2016-02-29', '2016-03-31', '2016-04-30',
               '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31',
               '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31'],
              dtype='datetime64[ns]', freq='M', tz=None)


In [101]:
df = pd.DataFrame(np.random.randn(12,4), index = dates, columns = list("ABCD"))

In [102]:
df

A         B         C         D
2016-01-31  0.909197 -0.142509  0.098814 -2.769066
2016-02-29 -0.176779 -1.408932 -1.290332 -1.834632
2016-03-31  0.377477 -1.035059 -0.810499  0.762375
2016-04-30  0.361142 -0.553092 -0.818236  0.055302
2016-05-31 -1.064325  0.152345 -0.474371 -0.220664
2016-06-30 -0.592509 -0.574188 -1.785074 -1.123949
2016-07-31  0.540477 -0.318197 -0.634260 -0.698973
2016-08-31 -1.529463 -0.262342 -1.051210 -0.979302
2016-09-30  0.699304 -0.921420 -0.855817  0.893309
2016-10-31 -0.724322  1.028907 -1.767534  0.196253
2016-11-30 -0.746984  0.798306  0.361986  1.532019
2016-12-31 -1.239011 -1.260112 -0.101727 -0.193036

In [103]:
my_dict = { 'A' : 1.,
   ....:                      'B' : pd.Timestamp('20130102'),
   ....:                      'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
   ....:                      'D' : np.array([3] * 4,dtype='int32'),
   ....:                      'E' : pd.Categorical(["test","train","test","train"]),
   ....:                      'F' : 'foo' }

In [104]:
my_dict

{'A': 1.0, 'B': Timestamp('2013-01-02 00:00:00'), 'C': 0    1
 1    1
 2    1
 3    1
 dtype: float32, 'D': array([3, 3, 3, 3], dtype=int32), 'E': [test, train, test, train]
 Categories (2, object): [test, train], 'F': 'foo'}

In [105]:
pd.Series(1,index=list(range(4)),dtype='float32')

0    1
1    1
2    1
3    1
dtype: float32

In [106]:
pd.Categorical(["test","train","test","train"])

[test, train, test, train]
Categories (2, object): [test, train]